# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab8cb94979a3b8f529f7bfd8d9a45521c1d36ff13c32add08db9b37a467df3fbcb9f8b3f4283d03e03c8610d9683c043ee32294ff763936fe7a3f74e09a18e7d

test:
  secret_key_base: f132ae246de3db5c553577ab6f51029315e3be7d8e61929df13b53fe50446753bdcd073193639151069c16786cbb0b450b1fb9ec62873e9bf4b6387c7d75d333

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
